// auto-generated from versus.txt
export const verses = [
  { verse: "Be still and know God is present.", reflection: "Pause your thinking. Quiet creates clarity." },
  { verse: "Trust God with all your heart.", reflection: "Stop overthinking. Choose trust first." },
  { verse: "Love your neighbor as yourself.", reflection: "Treat people with basic respect today." },
  { verse: "Ask and you will receive.", reflection: "Speak your needs clearly." },
  { verse: "Seek and you will find.", reflection: "Take one clear step forward." },
  { verse: "Knock and the door opens.", reflection: "Consistency brings access." },
  { verse: "Faith moves mountains.", reflection: "Small belief creates movement." },
  { verse: "Do not fear. God is with you.", reflection: "Fear shrinks when support feels real." },
  { verse: "Light shines in darkness.", reflection: "Your effort matters even in hard times." },
  { verse: "The truth sets you free.", reflection: "Honesty reduces mental weight." },
  { verse: "Give and it returns.", reflection: "Generosity builds momentum." },
  { verse: "Forgive and release others.", reflection: "Letting go frees your energy." },
  { verse: "Peace surpasses understanding.", reflection: "Calm comes before logic." },
  { verse: "Love remains.", reflection: "Choose love over control." },
  { verse: "Hope anchors the soul.", reflection: "Hold steady during uncertainty." },
  { verse: "Joy comes in the morning.", reflection: "Emotions change with time." },
  { verse: "Walk humbly.", reflection: "Stay open to learning." },
  { verse: "Serve one another.", reflection: "Help without seeking credit." },
  { verse: "God strengthens the weary.", reflection: "Rest restores focus." },
  { verse: "Patience produces growth.", reflection: "Progress takes time." },
  { verse: "Kind words heal.", reflection: "Speak with care." },
  { verse: "Plans succeed with guidance.", reflection: "Ask before acting." },
  { verse: "Do good without reward.", reflection: "Integrity builds trust." },
  { verse: "God directs your steps.", reflection: "Focus on the next step." },
  { verse: "Life flows from the heart.", reflection: "Protect your inner state." },
  { verse: "Do what is right.", reflection: "Simple choices shape outcomes." },
  { verse: "Love covers many faults.", reflection: "Grace reduces conflict." },
  { verse: "Faith without action fades.", reflection: "Move with intention." },
  { verse: "God gives wisdom freely.", reflection: "Ask better questions." },
  { verse: "Peace follows obedience.", reflection: "Alignment lowers stress." },
  { verse: "Be courageous.", reflection: "Act despite fear." },
  { verse: "Mercy triumphs.", reflection: "Choose compassion." },
  { verse: "Hope renews strength.", reflection: "Rest fuels endurance." },
  { verse: "Walk in the light.", reflection: "Be transparent." },
  { verse: "God listens.", reflection: "Speak honestly." },
  { verse: "Humility brings honor.", reflection: "Ego slows growth." },
  { verse: "God provides daily.", reflection: "Focus on today." },
  { verse: "Choose life.", reflection: "Pick what supports growth." },
  { verse: "God sees the heart.", reflection: "Intent matters." },
  { verse: "Speak truth.", reflection: "Clear words prevent confusion." },
  { verse: "Love builds.", reflection: "Connection creates stability." },
  { verse: "Do not worry about tomorrow.", reflection: "Plan lightly. Live fully." },
  { verse: "God restores.", reflection: "Recovery stays possible." },
  { verse: "Faith brings peace.", reflection: "Trust reduces tension." },
  { verse: "Walk wisely.", reflection: "Think before reacting." },
  { verse: "God lifts the humble.", reflection: "Stay grounded." },
  { verse: "Give thanks always.", reflection: "Gratitude shifts perspective." },
  { verse: "God is near.", reflection: "Support exists now." },
  { verse: "Strength rises through joy.", reflection: "Protect your mood." },
  { verse: "Seek peace.", reflection: "Reduce friction." },
  { verse: "God teaches.", reflection: "Stay teachable." },
  { verse: "Love patiently.", reflection: "Slow reactions help." },
  { verse: "God forgives.", reflection: "Release shame." },
  { verse: "Stand firm.", reflection: "Hold boundaries." },
  { verse: "God sees effort.", reflection: "Consistency counts." },
  { verse: "Choose understanding.", reflection: "Listen longer." },
  { verse: "Truth brings clarity.", reflection: "Facts calm emotion." },
  { verse: "God supplies needs.", reflection: "Avoid scarcity thinking." },
  { verse: "Light guides paths.", reflection: "Clarity follows action." },
  { verse: "Serve quietly.", reflection: "Impact grows silently." },
  { verse: "God renews minds.", reflection: "Update old patterns." },
  { verse: "Choose kindness.", reflection: "Small acts matter." },
  { verse: "God protects.", reflection: "You are safe enough." },
  { verse: "Peace guards the heart.", reflection: "Calm prevents mistakes." },
  { verse: "Faith grows through trials.", reflection: "Stress builds skill." },
  { verse: "God values obedience.", reflection: "Follow through." },
  { verse: "Speak life.", reflection: "Encouragement changes tone." },
  { verse: "God remains faithful.", reflection: "Stability exists." },
  { verse: "Walk in love.", reflection: "Lead with care." },
  { verse: "God rewards diligence.", reflection: "Show up daily." },
  { verse: "Hope stays alive.", reflection: "Expect improvement." },
  { verse: "God hears prayers.", reflection: "Voice concerns." },
  { verse: "Love endures.", reflection: "Stay steady." },
  { verse: "God strengthens resolve.", reflection: "Inner strength develops." },
  { verse: "Choose wisdom.", reflection: "Pause before action." },
  { verse: "God restores joy.", reflection: "Energy returns." },
  { verse: "Live upright.", reflection: "Simple ethics work." },
  { verse: "God sees struggles.", reflection: "You are noticed." },
  { verse: "Peace follows trust.", reflection: "Relax control." },
  { verse: "God teaches patience.", reflection: "Wait builds skill." },
  { verse: "Love gives freely.", reflection: "Detach from outcome." },
  { verse: "God builds character.", reflection: "Pressure shapes behavior." },
  { verse: "Stand in truth.", reflection: "Avoid shortcuts." },
  { verse: "God gives rest.", reflection: "Recovery improves results." },
  { verse: "Walk faithfully.", reflection: "Daily effort counts." },
  { verse: "God invites trust.", reflection: "Release control." },
  { verse: "Love leads.", reflection: "Set the tone." },
  { verse: "God renews hope.", reflection: "Outlook shifts." },
  { verse: "Choose faith.", reflection: "Focus forward." },
  { verse: "God works quietly.", reflection: "Progress stays unseen." },
  { verse: "Peace stays available.", reflection: "Slow your pace." },
  { verse: "God guides choices.", reflection: "Seek alignment." },
  { verse: "Love heals.", reflection: "Connection repairs damage." },
  { verse: "God strengthens hearts.", reflection: "Resilience grows." },
  { verse: "Choose humility.", reflection: "Stay grounded." },
  { verse: "God brings clarity.", reflection: "Confusion passes." },
  { verse: "Live generously.", reflection: "Abundance thinking helps." },
  { verse: "God restores peace.", reflection: "Calm returns." },
  { verse: "Choose forgiveness.", reflection: "Drop resentment." },
  { verse: "God shapes paths.", reflection: "Direction forms." },
  { verse: "Love listens.", reflection: "Presence matters." },
  { verse: "God gives courage.", reflection: "Act anyway." },
  { verse: "Choose stillness.", reflection: "Noise clouds judgment." },
  { verse: "God supports effort.", reflection: "You are supported." },
  { verse: "Love protects.", reflection: "Care creates safety." },
  { verse: "God renews strength.", reflection: "Energy cycles back." },
  { verse: "Choose truth.", reflection: "Honesty simplifies life." },
  { verse: "God values faithfulness.", reflection: "Consistency wins." },
  { verse: "Love serves.", reflection: "Focus outward." },
  { verse: "God provides wisdom.", reflection: "Seek insight." },
  { verse: "Choose peace.", reflection: "Conflict drains energy." },
  { verse: "God restores focus.", reflection: "Clarity returns." },
  { verse: "Love remains strong.", reflection: "Commitment matters." },
  { verse: "God holds tomorrow.", reflection: "Stay present." },
  { verse: "Choose growth.", reflection: "Discomfort teaches." },
  { verse: "God walks with you.", reflection: "You are accompanied." },
  { verse: "Love guides action.", reflection: "Values lead decisions." },
  { verse: "Be still and recognize God.", reflection: "Silence clears mental noise." },
  { verse: "Trust fully with your heart.", reflection: "Release control early." },
  { verse: "Love others as yourself.", reflection: "Treat people fairly today." },
  { verse: "Ask with intention.", reflection: "State needs clearly." },
  { verse: "Seek with effort.", reflection: "Action brings answers." },
  { verse: "Knock persistently.", reflection: "Consistency opens paths." },
  { verse: "Faith moves obstacles.", reflection: "Belief fuels momentum." },
  { verse: "Fear fades with presence.", reflection: "You are supported." },
  { verse: "Light overcomes darkness.", reflection: "Progress exists even now." },
  { verse: "Truth frees the mind.", reflection: "Honesty reduces stress." },
  { verse: "Give openly.", reflection: "Energy returns." },
  { verse: "Forgive completely.", reflection: "Release mental weight." },
  { verse: "Peace goes beyond logic.", reflection: "Calm stabilizes decisions." },
  { verse: "Love remains constant.", reflection: "Choose connection." },
  { verse: "Hope anchors endurance.", reflection: "Stay steady." },
  { verse: "Joy returns after struggle.", reflection: "Time shifts emotion." },
  { verse: "Walk humbly.", reflection: "Ego blocks learning." },
  { verse: "Serve willingly.", reflection: "Value grows quietly." },
  { verse: "Strength renews the tired.", reflection: "Rest matters." },
  { verse: "Patience builds outcomes.", reflection: "Timing shapes results." },
  { verse: "Kind words heal.", reflection: "Tone changes outcomes." },
  { verse: "Guidance improves plans.", reflection: "Ask before acting." },
  { verse: "Do good consistently.", reflection: "Integrity compounds." },
  { verse: "Steps gain direction.", reflection: "Focus on today." },
  { verse: "Life flows from thought.", reflection: "Guard mindset." },
  { verse: "Choose what is right.", reflection: "Small choices matter." },
  { verse: "Love absorbs mistakes.", reflection: "Grace reduces friction." },
  { verse: "Faith requires action.", reflection: "Move forward." },
  { verse: "Wisdom arrives when asked.", reflection: "Pause and seek insight." },
  { verse: "Peace follows alignment.", reflection: "Inner order lowers stress." },
  { verse: "Courage begins movement.", reflection: "Act despite fear." },
  { verse: "Mercy outperforms judgment.", reflection: "Compassion resolves conflict." },
  { verse: "Hope restores energy.", reflection: "Outlook drives stamina." },
  { verse: "Walk openly.", reflection: "Transparency builds trust." },
  { verse: "God listens.", reflection: "Speak honestly." },
  { verse: "Humility attracts respect.", reflection: "Stay grounded." },
  { verse: "Daily provision exists.", reflection: "Focus short term." },
  { verse: "Choose life affirmatively.", reflection: "Support growth." },
  { verse: "Intent defines value.", reflection: "Motives shape results." },
  { verse: "Speak truth clearly.", reflection: "Avoid confusion." },
  { verse: "Love strengthens systems.", reflection: "Connection stabilizes." },
  { verse: "Release future worry.", reflection: "Stay present." },
  { verse: "Restoration remains possible.", reflection: "Recovery exists." },
  { verse: "Faith calms emotion.", reflection: "Trust stabilizes." },
  { verse: "Choose wisdom daily.", reflection: "React less." },
  { verse: "Lifting follows humility.", reflection: "Stay balanced.Q" },
  { verse: "Gratitude reshapes thinking.", reflection: "Notice positives." },
  { verse: "Presence stays near.", reflection: "Support exists." },
  { verse: "Joy increases strength.", reflection: "Protect mood." },
  { verse: "Seek peace actively.", reflection: "Reduce tension." },
  { verse: "Learning remains ongoing.", reflection: "Stay open." },
  { verse: "Patience slows conflict.", reflection: "Pause first." },
  { verse: "Forgiveness clears focus.", reflection: "Drop guilt." },
  { verse: "Stand firm.", reflection: "Hold boundaries." },
  { verse: "Effort counts.", reflection: "Show up." },
  { verse: "Understanding lowers conflict.", reflection: "Listen longer." },
  { verse: "Clarity follows truth.", reflection: "Facts calm emotion." },
  { verse: "Needs receive support.", reflection: "Avoid scarcity." },
  { verse: "Light clarifies direction.", reflection: "Act to see." },
  { verse: "Quiet service matters.", reflection: "Impact grows unseen." },
  { verse: "Mind renewal exists.", reflection: "Change patterns." },
  { verse: "Choose kindness.", reflection: "Small acts count." },
  { verse: "Protection surrounds effort.", reflection: "Stay steady." },
  { verse: "Peace guards emotion.", reflection: "Calm prevents error." },
  { verse: "Pressure builds capacity.", reflection: "Stress teaches." },
  { verse: "Obedience creates order.", reflection: "Follow through." },
  { verse: "Words shape reality.", reflection: "Encourage intentionally." },
  { verse: "Faithfulness persists.", reflection: "Stability exists." },
  { verse: "Love leads decisions.", reflection: "Care guides action." },
  { verse: "Diligence brings results.", reflection: "Daily effort wins." },
  { verse: "Hope stays alive.", reflection: "Expect progress." },
  { verse: "Prayers receive attention.", reflection: "Voice concerns." },
  { verse: "Endurance sustains growth.", reflection: "Stay committed." },
  { verse: "Resolve strengthens internally.", reflection: "Mental strength grows." },
  { verse: "Wisdom simplifies choices.", reflection: "Pause first." },
  { verse: "Joy returns.", reflection: "Energy cycles." },
  { verse: "Integrity works.", reflection: "Simple ethics succeed." },
  { verse: "Struggles receive notice.", reflection: "You matter." },
  { verse: "Trust reduces anxiety.", reflection: "Relax grip." },
  { verse: "Waiting builds skill.", reflection: "Timing matters." },
  { verse: "Generosity frees thinking.", reflection: "Detach outcomes." },
  { verse: "Character forms under pressure.", reflection: "Growth requires resistance." },
  { verse: "Truth anchors behavior.", reflection: "Avoid shortcuts." },
  { verse: "Rest restores output.", reflection: "Recovery boosts results." },
  { verse: "Faithfulness compounds.", reflection: "Consistency builds trust." },
  { verse: "Trust invites calm.", reflection: "Release tension." },
  { verse: "Love sets tone.", reflection: "Model behavior." },
  { verse: "Hope refreshes outlook.", reflection: "Perspective shifts." },
  { verse: "Belief directs focus.", reflection: "Aim forward." },
  { verse: "Quiet work progresses.", reflection: "Results appear later." },
  { verse: "Peace stays accessible.", reflection: "Slow pace." },
  { verse: "Direction follows alignment.", reflection: "Seek clarity." },
  { verse: "Love repairs damage.", reflection: "Connection heals." },
  { verse: "Strength grows steadily.", reflection: "Resilience builds." },
  { verse: "Humility stabilizes.", reflection: "Stay grounded." },
  { verse: "Confusion passes.", reflection: "Clarity returns." },
  { verse: "Generosity expands mindset.", reflection: "Think abundance." },
  { verse: "Peace restores balance.", reflection: "Calm returns." },
  { verse: "Forgiveness frees capacity.", reflection: "Drop resentment." },
  { verse: "Paths take shape.", reflection: "Direction emerges." },
  { verse: "Listening builds trust.", reflection: "Presence matters." },
  { verse: "Courage fuels action.", reflection: "Move anyway." },
  { verse: "Stillness improves judgment.", reflection: "Reduce noise." },
  { verse: "Effort receives backing.", reflection: "Support exists." },
  { verse: "Care creates safety.", reflection: "Protect others." },
  { verse: "Strength renews.", reflection: "Energy returns." },
  { verse: "Truth simplifies life.", reflection: "Honesty clears paths." },
  { verse: "Consistency earns value.", reflection: "Stay steady." },
  { verse: "Service strengthens purpose.", reflection: "Focus outward." },
  { verse: "Insight remains available.", reflection: "Seek wisdom." },
  { verse: "Peace preserves energy.", reflection: "Avoid conflict." },
  { verse: "Focus returns.", reflection: "Mental order follows." },
  { verse: "Commitment sustains value.", reflection: "Stay engaged." },
  { verse: "Tomorrow stays held.", reflection: "Remain present." },
  { verse: "Growth requires discomfort.", reflection: "Lean in." },
  { verse: "Presence accompanies you.", reflection: "You are supported." },
  { verse: "Walk with integrity.", reflection: "Consistency builds trust." },
  { verse: "Guard your thoughts.", reflection: "Input shapes output." },
  { verse: "Choose wisdom over impulse.", reflection: "Pause before acting." },
  { verse: "Love acts patiently.", reflection: "Slow responses help." },
  { verse: "Peace settles the mind.", reflection: "Calm improves judgment." },
  { verse: "Faith steadies action.", reflection: "Confidence grows through trust." },
  { verse: "Speak with purpose.", reflection: "Words influence direction." },
  { verse: "Seek understanding first.", reflection: "Listening prevents friction." },
  { verse: "Joy strengthens resolve.", reflection: "Mood affects stamina." },
  { verse: "Remain teachable.", reflection: "Growth requires openness." },
  { verse: "Hope sustains effort.", reflection: "Expectation fuels persistence." },
  { verse: "Serve without attention.", reflection: "Impact multiplies quietly." },
  { verse: "Release control.", reflection: "Flexibility lowers stress." },
  { verse: "Walk faithfully daily.", reflection: "Small steps compound." },
  { verse: "Truth clarifies paths.", reflection: "Facts reduce emotion." },
  { verse: "Choose compassion.", reflection: "Empathy eases tension." },
  { verse: "Patience matures outcomes.", reflection: "Time shapes results." },
  { verse: "Focus on today.", reflection: "Presence sharpens action." },
  { verse: "Give freely.", reflection: "Flow returns." },
  { verse: "Strength rises through rest.", reflection: "Recovery improves output." },
  { verse: "Act with courage.", reflection: "Motion beats fear." },
  { verse: "Protect inner peace.", reflection: "Boundaries preserve energy." },
  { verse: "Practice gratitude.", reflection: "Awareness shifts mindset." },
  { verse: "Stay aligned.", reflection: "Clarity follows values." },
  { verse: "Love leads speech.", reflection: "Tone shapes response." },
  { verse: "Trust develops resilience.", reflection: "Stability grows inside." },
  { verse: "Choose humility.", reflection: "Learning accelerates." },
  { verse: "Speak gently.", reflection: "Soft words deescalate." },
  { verse: "Remain consistent.", reflection: "Repetition builds mastery." },
  { verse: "Let go of resentment.", reflection: "Mental space opens." },
  { verse: "Hope directs focus.", reflection: "Aim forward." },
  { verse: "Practice self control.", reflection: "Discipline supports freedom." },
  { verse: "Seek clarity.", reflection: "Questions improve decisions." },
  { verse: "Offer forgiveness.", reflection: "Release restores balance." },
  { verse: "Act honestly.", reflection: "Transparency simplifies life." },
  { verse: "Remain steady.", reflection: "Calm sustains effort." },
  { verse: "Love repairs strain.", reflection: "Connection heals rifts." },
  { verse: "Choose stillness.", reflection: "Quiet sharpens thinking." },
  { verse: "Stay diligent.", reflection: "Effort compounds daily." },
  { verse: "Embrace learning.", reflection: "Mistakes teach." },
  { verse: "Value patience.", reflection: "Timing matters." },
  { verse: "Practice kindness.", reflection: "Small acts ripple." },
  { verse: "Stay present.", reflection: "Attention drives quality." },
  { verse: "Choose peace.", reflection: "Conflict drains energy." },
  { verse: "Speak truthfully.", reflection: "Clear words prevent drift." },
  { verse: "Trust the process.", reflection: "Progress unfolds." },
  { verse: "Serve others well.", reflection: "Purpose strengthens." },
  { verse: "Stay grounded.", reflection: "Balance supports clarity." },
  { verse: "Hope renews drive.", reflection: "Outlook fuels action." },
  { verse: "Practice generosity.", reflection: "Abundance thinking grows." },
  { verse: "Release fear.", reflection: "Action builds confidence." },
  { verse: "Stay aligned internally.", reflection: "Order reduces stress." },
  { verse: "Love without agenda.", reflection: "Care builds trust." },
  { verse: "Choose discipline.", reflection: "Structure supports freedom." },
  { verse: "Rest intentionally.", reflection: "Energy returns faster." },
  { verse: "Seek wisdom daily.", reflection: "Insight compounds." },
  { verse: "Act with integrity.", reflection: "Character shapes results." },
  { verse: "Remain calm.", reflection: "Stability guides others." },
  { verse: "Practice patience.", reflection: "Impulse fades." },
  { verse: "Encourage others.", reflection: "Support multiplies impact." },
  { verse: "Focus your effort.", reflection: "Clarity improves output." },
  { verse: "Speak with clarity.", reflection: "Precision saves time." },
  { verse: "Trust builds peace.", reflection: "Anxiety fades." },
  { verse: "Stay resilient.", reflection: "Pressure builds strength." },
  { verse: "Release comparison.", reflection: "Focus improves." },
  { verse: "Serve consistently.", reflection: "Reliability matters." },
  { verse: "Practice awareness.", reflection: "Attention reveals options." },
  { verse: "Choose hope.", reflection: "Optimism sustains effort." },
  { verse: "Walk thoughtfully.", reflection: "Intention shapes direction." },
  { verse: "Act generously.", reflection: "Giving expands mindset." },
  { verse: "Remain flexible.", reflection: "Adaptation supports growth." },
  { verse: "Speak with kindness.", reflection: "Respect lowers defenses." },
  { verse: "Stay patient.", reflection: "Progress continues." },
  { verse: "Choose learning.", reflection: "Curiosity fuels growth." },
  { verse: "Protect focus.", reflection: "Distraction weakens results." },
  { verse: "Encourage progress.", reflection: "Momentum matters." },
  { verse: "Stay truthful.", reflection: "Integrity stabilizes outcomes." },
  { verse: "Practice humility.", reflection: "Ego clouds judgment." },
  { verse: "Choose compassion.", reflection: "Understanding reduces conflict." },
  { verse: "Remain steady under stress.", reflection: "Calm leads." },
  { verse: "Focus inward first.", reflection: "Clarity begins inside." },
  { verse: "Act purposefully.", reflection: "Direction sharpens." },
  { verse: "Release tension.", reflection: "Relaxation restores clarity." },
  { verse: "Stay disciplined.", reflection: "Routine builds reliability." },
  { verse: "Offer grace.", reflection: "Tolerance preserves relationships." },
  { verse: "Seek peace actively.", reflection: "Harmony requires effort." },
  { verse: "Practice consistency.", reflection: "Trust forms over time." },
  { verse: "Choose courage.", reflection: "Fear loses control." },
  { verse: "Remain observant.", reflection: "Awareness prevents mistakes." },
  { verse: "Speak constructively.", reflection: "Solutions matter." },
  { verse: "Value rest.", reflection: "Sustainability improves results." },
  { verse: "Act with care.", reflection: "Precision matters." },
  { verse: "Stay hopeful.", reflection: "Expectation drives effort." },
  { verse: "Serve sincerely.", reflection: "Authenticity builds loyalty." },
  { verse: "Protect balance.", reflection: "Extremes exhaust." },
  { verse: "Choose alignment.", reflection: "Values guide action." },
  { verse: "Practice forgiveness.", reflection: "Release frees capacity." },
  { verse: "Remain attentive.", reflection: "Presence improves outcomes." },
  { verse: "Speak intentionally.", reflection: "Purpose directs words." },
  { verse: "Stay committed.", reflection: "Follow through matters." },
  { verse: "Choose calm.", reflection: "Emotion clouds logic." },
  { verse: "Act ethically.", reflection: "Trust follows." },
  { verse: "Remain patient with growth.", reflection: "Change takes time." },
  { verse: "Practice generosity daily.", reflection: "Habits shape identity." },
  { verse: "Focus on progress.", reflection: "Momentum beats perfection." },
  { verse: "Encourage clarity.", reflection: "Guidance helps others." },
  { verse: "Stay grounded in values.", reflection: "Consistency stabilizes choices." },
  { verse: "Choose kindness in conflict.", reflection: "Respect lowers resistance." },
  { verse: "Remain adaptable.", reflection: "Flexibility supports success." },
  { verse: "Speak honestly.", reflection: "Truth simplifies paths." },
  { verse: "Protect energy.", reflection: "Focus preserves stamina." },
  { verse: "Act with intention.", reflection: "Purpose sharpens results." },
  { verse: "Stay curious.", reflection: "Questions expand insight." },
  { verse: "Serve with consistency.", reflection: "Reliability builds confidence." },
  { verse: "Choose peace internally.", reflection: "Calm starts within." },
  { verse: "Remain disciplined.", reflection: "Structure supports goals." },
  { verse: "Practice patience daily.", reflection: "Timing aligns outcomes." },
  { verse: "Speak with respect.", reflection: "Tone shapes response." },
  { verse: "Stay resilient daily.", reflection: "Endurance develops." },
  { verse: "Choose steady paths.", reflection: "Consistency reduces friction." },
  { verse: "Guard your focus.", reflection: "Attention drives results." },
  { verse: "Walk with purpose.", reflection: "Direction sharpens effort." },
  { verse: "Practice restraint.", reflection: "Control preserves energy." },
  { verse: "Speak with clarity.", reflection: "Clear words save time." },
  { verse: "Act with patience.", reflection: "Timing shapes success." },
  { verse: "Remain grounded.", reflection: "Balance improves judgment." },
  { verse: "Value simplicity.", reflection: "Less clutter improves focus." },
  { verse: "Choose trust.", reflection: "Confidence stabilizes action." },
  { verse: "Serve with care.", reflection: "Quality builds respect." },
  { verse: "Release urgency.", reflection: "Calm improves outcomes." },
  { verse: "Stay present.", reflection: "Awareness improves decisions." },
  { verse: "Practice discipline.", reflection: "Structure supports freedom." },
  { verse: "Lead with empathy.", reflection: "Understanding lowers resistance." },
  { verse: "Choose consistency.", reflection: "Reliability builds momentum." },
  { verse: "Focus on effort.", reflection: "Process drives results." },
  { verse: "Speak thoughtfully.", reflection: "Intent shapes impact." },
  { verse: "Remain flexible.", reflection: "Adaptation supports progress." },
  { verse: "Protect calm.", reflection: "Stability prevents error." },
  { verse: "Act deliberately.", reflection: "Purpose strengthens action." },
  { verse: "Practice gratitude daily.", reflection: "Perspective improves mood." },
  { verse: "Choose humility.", reflection: "Learning accelerates growth." },
  { verse: "Serve quietly.", reflection: "Impact expands naturally." },
  { verse: "Stay attentive.", reflection: "Details matter." },
  { verse: "Release excess.", reflection: "Simplicity sharpens clarity." },
  { verse: "Act with resolve.", reflection: "Commitment sustains progress." },
  { verse: "Choose patience.", reflection: "Waiting improves alignment." },
  { verse: "Speak constructively.", reflection: "Solutions move forward." },
  { verse: "Remain resilient.", reflection: "Pressure builds capacity." },
  { verse: "Focus forward.", reflection: "Momentum increases." },
  { verse: "Practice generosity.", reflection: "Giving expands outlook." },
  { verse: "Choose awareness.", reflection: "Observation prevents mistakes." },
  { verse: "Stay disciplined.", reflection: "Habits shape outcomes." },
  { verse: "Act honestly.", reflection: "Integrity simplifies paths." },
  { verse: "Lead calmly.", reflection: "Composure guides others." },
  { verse: "Choose kindness.", reflection: "Respect builds trust." },
  { verse: "Remain curious.", reflection: "Questions expand insight." },
  { verse: "Protect energy.", reflection: "Sustainability matters." },
  { verse: "Act with care.", reflection: "Precision improves quality." },
  { verse: "Choose learning.", reflection: "Growth follows curiosity." },
  { verse: "Speak gently.", reflection: "Soft tone reduces friction." },
  { verse: "Stay aligned.", reflection: "Values guide action." },
  { verse: "Practice forgiveness.", reflection: "Release restores balance." },
  { verse: "Focus on clarity.", reflection: "Understanding drives action." },
  { verse: "Remain patient.", reflection: "Progress unfolds steadily." },
  { verse: "Choose courage.", reflection: "Action builds confidence." },
  { verse: "Serve consistently.", reflection: "Reliability earns trust." },
  { verse: "Protect balance.", reflection: "Moderation sustains effort." },
  { verse: "Act intentionally.", reflection: "Purpose sharpens results." },
  { verse: "Stay grounded internally.", reflection: "Stability improves decisions." },
  { verse: "Practice awareness.", reflection: "Attention reveals opportunity." },
  { verse: "Choose peace.", reflection: "Calm preserves focus." },
  { verse: "Speak precisely.", reflection: "Accuracy prevents drift." },
  { verse: "Remain steady.", reflection: "Consistency compounds." },
  { verse: "Value rest.", reflection: "Recovery improves output." },
  { verse: "Act ethically.", reflection: "Character drives outcomes." },
  { verse: "Stay hopeful.", reflection: "Expectation fuels effort." },
  { verse: "Practice restraint daily.", reflection: "Discipline supports clarity." },
  { verse: "Focus inward.", reflection: "Self awareness guides action." },
  { verse: "Remain adaptable.", reflection: "Flexibility supports success." },
  { verse: "Choose compassion.", reflection: "Empathy resolves tension." },
  { verse: "Speak with respect.", reflection: "Dignity strengthens dialogue." },
  { verse: "Stay committed.", reflection: "Follow through matters." },
  { verse: "Practice patience always.", reflection: "Timing aligns results." },
  { verse: "Choose simplicity.", reflection: "Focus improves execution." },
  { verse: "Act deliberately.", reflection: "Intent guides motion." },
  { verse: "Remain attentive.", reflection: "Presence improves quality." },
  { verse: "Protect focus.", reflection: "Distraction weakens effort." },
  { verse: "Choose generosity.", reflection: "Abundance mindset grows." },
  { verse: "Stay resilient daily.", reflection: "Endurance develops strength." },
  { verse: "Speak with intention.", reflection: "Purpose directs language." },
  { verse: "Remain disciplined daily.", reflection: "Routine builds reliability." },
  { verse: "Choose calm responses.", reflection: "Control shapes outcomes." },
  { verse: "Act with humility.", reflection: "Openness improves learning." },
  { verse: "Stay observant.", reflection: "Awareness sharpens judgment." },
  { verse: "Practice consistency daily.", reflection: "Trust forms steadily." },
  { verse: "Choose alignment.", reflection: "Values reduce conflict." },
  { verse: "Speak truth clearly.", reflection: "Honesty stabilizes paths." },
  { verse: "Remain focused.", reflection: "Clarity increases speed." },
  { verse: "Protect boundaries.", reflection: "Limits preserve energy." },
  { verse: "Choose diligence.", reflection: "Effort compounds value." },
  { verse: "Act with purpose daily.", reflection: "Direction sustains progress." },
  { verse: "Stay present always.", reflection: "Attention anchors action." },
  { verse: "Practice generosity often.", reflection: "Giving strengthens connection." },
  { verse: "Choose patience again.", reflection: "Growth requires time." },
  { verse: "Speak calmly.", reflection: "Tone influences outcome." },
  { verse: "Remain grounded daily.", reflection: "Balance supports clarity." },
  { verse: "Act steadily.", reflection: "Consistency builds mastery." },
  { verse: "Choose awareness first.", reflection: "Observation guides response." },
  { verse: "Stay disciplined internally.", reflection: "Self control sustains effort." },
  { verse: "Practice kindness often.", reflection: "Small acts compound." },
  { verse: "Choose focus.", reflection: "Priority drives progress." },
  { verse: "Act responsibly.", reflection: "Ownership builds trust." },
  { verse: "Remain flexible always.", reflection: "Change supports growth." },
  { verse: "Speak with care.", reflection: "Words carry weight." },
  { verse: "Stay resilient under pressure.", reflection: "Strength develops gradually." },
  { verse: "Choose learning daily.", reflection: "Curiosity fuels improvement." },
  { verse: "Act ethically always.", reflection: "Integrity shapes reputation." },
  { verse: "Remain calm under stress.", reflection: "Stability guides action." },
  { verse: "Practice patience consistently.", reflection: "Timing reveals opportunity." },
  { verse: "Choose compassion daily.", reflection: "Understanding eases tension." },
  { verse: "Speak thoughtfully always.", reflection: "Intent shapes meaning." },
  { verse: "Stay aligned daily.", reflection: "Values guide behavior." },
  { verse: "Act intentionally always.", reflection: "Purpose directs effort." },
  { verse: "Remain steady daily.", reflection: "Consistency sustains success." },
] as const;
